---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  enabled: false
platforms:
  - name: centos-7
    box: centos/7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: 
        - 204
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
