---
- name: Template .pgpass
  template:
    src: pgpass.j2
    dest: "{{ postgresql_homedir }}/.pgpass"
    owner: postgres
    group: postgres
    mode: 0400
  when: postgresql_pgpass_entries|length > 0
...
