---
- name: Setup grafana repo
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.name }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: yes
    gpgkey:
      - https://packages.grafana.com/gpg.key
    file: grafana
    repo_gpgcheck: yes
    enabled: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    sslverify: yes
  loop:
    - name: grafana
      baseurl: https://packages.grafana.com/oss/rpm

- name: Yum install packages
  yum:
    name: "{{ prom_grafana_packages }}"
  when: ansible_distribution_major_version|int <= 7

- name: Dnf install packages
  dnf:
    name: "{{ prom_grafana_packages }}"
  when: ansible_distribution_major_version|int >= 8

- name: Grafana service state
  systemd:
    name: grafana-server.service
    enabled: yes
    state: started
...
