---
- name: Get and unpack node_exporter archive
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ prom_node_exporter_version }}/node_exporter-{{ prom_node_exporter_version }}.linux-amd64.tar.gz"
    remote_src: yes
    dest: /usr/local/bin
    extra_opts:
      - --strip-components=1
      - "node_exporter-{{ prom_node_exporter_version }}.linux-amd64/node_exporter"
    creates: "/var/lib/flags/node_exporter_v{{ prom_node_exporter_version }}_installed"
  register: prom_reg_exporter_unarch

- name: Touch install node_exporter flag
  file:
    path: "/var/lib/flags/node_exporter_v{{ prom_node_exporter_version }}_installed"
    state: touch
  when: prom_reg_exporter_unarch.changed

- name: Copy node_exporter.service
  copy:
    src: "{{ item.path }}"
    dest: "/{{ item.path }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - path: etc/systemd/system/node_exporter.service
  notify:
    - reload systemd
    - restart node_exporter

- name: Node_exporter service state
  systemd:
    name: node_exporter.service
    enabled: yes
    state: started
...
